instantiate:
  _target_: gadme.datasets.esc50_datamodule.ESC50
  data_dir: ${paths.dataset_path}
  dataset_name: esc50
  feature_extractor_name: ${model.instantiate.model.checkpoint}
  hf_path: ashraq/esc50
  hf_name: None
  seed: ${random_seed}
  train_batch_size: ${train_batch_size}
  eval_batch_size: ${eval_batch_size}
  val_split: ${val_split}
  column_list: ["input_values", "target"]
extras:
  num_classes: 50
