instantiate:
  _target_: gadme.datasets.sapsucker_datamodule.SapsuckerWoods
  data_dir: ${paths.dataset_path}
  dataset_name: sapsucker
  feature_extractor_name: ${model.instantiate.model.checkpoint}
  hf_path: DBD-research-group/gadme_v1_1
  hf_name: NA_subset500
  seed: ${seed}
  train_batch_size: ${train_batch_size}
  eval_batch_size: ${eval_batch_size}
  val_split: ${val_split}
  column_list: ["input_values", "ebird_code"]
extras:
  num_classes: 500




