model:
  _target_: src.modules.models.ast.ASTSequenceClassifier
  checkpoint: MIT/ast-finetuned-audioset-10-10-0.4593
  local_checkpoint: null
  num_classes: ${datamodule.dataset.n_classes}
  cache_dir: ${paths.dataset_path}/models/

  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null

model_name: ast
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_spectrogram: True
normalize_waveform: "instance_normalization"














