model:
  _target_: src.modules.models.ast.ASTSequenceClassifier
  checkpoint: MIT/ast-finetuned-audioset-10-10-0.4593
  #checkpoint: null
  num_classes: ${datamodule.dataset.n_classes}
  cache_dir: ${paths.dataset_path}/models/


model_name: ast
model_type: vision
torch_compile: false
sampling_rate: 32_000















