# @package _global_
defaults:
  - _self_
  - datamodule: high_sierras
  - module: multilabel
  - callbacks: default
  - paths: default
  - trainer: single_gpu
  - logger: wandb
  - hydra: default
  - extras: default

  - experiment: null
  - hparams_search: null
  - debug: null

task_name: "train"
ckpt_path: null
seed: 1

module:
  network: ast
logger:
  wandb:
    mode: online
train: True
test: True
save_state_dict: True

