#PER
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: amazon_basin
  hf_path: DBD-research-group/gadme_v1
  hf_name: amazon_basin
  seed: ${seed}
  n_classes: 133
  n_workers: 3
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}






