#UHH
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults:
  - _self_
  - transforms: bird_default.yaml
  - extractors: default_aug.yaml
  - loaders: default.yaml

dataset:
  mode: "hf" # local or hf
  data_dir: ${paths.dataset_path}
  dataset_name: hawaiian_islands
  hf_path: DBD-research-group/gadme_v1
  hf_name: hawaiian_islands
  seed: ${seed}
  n_classes: 28
  n_workers: 3
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  classlimit: 500
  eventlimit: 5



