#SSW
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults:
  - _self_
  - transforms: bird_default.yaml
  - extractors: default_aug.yaml
  - loaders: default.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: sapsucker_woods
  hf_path: DBD-research-group/gadme_v1_1
  hf_name: sapsucker_woods
  seed: ${seed}
  n_classes: 82
  n_workers: 3
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}



