#xcm
_target_: src.datamodule.pretrain_datamodule.PretrainDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: XCM
  hf_path: DBD-research-group/gadme
  hf_name: XCM
  seed: ${seed}
  n_classes: 409
  n_workers: 1
  val_split: 0.05
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  class_weights_loss: null
  class_weights_sampler: null
  classlimit: 500
  eventlimit: 5







