# @package _global_
task_name: debug

defaults:
  - override /module: multilabel.yaml
  - override /module/network: efficientnet.yaml
  - override /datamodule: HSN.yaml
  #- override /callbacks: default.yaml 
  - override /trainer: single_gpu.yaml
  - override /datamodule/transforms: bird_default_multilabel.yaml
  - override /callbacks: cluster.yaml
  #- override /datamodule/transforms/spectrogram_augmentations: none.yaml
  #- override /datamodule/transforms/waveform_augmentations: none.yaml

#ckpt_path: "/home/lrauch/projects/GADME/gadme/output/train/runs/xenocanto_m_withoutnd/eat/2024-01-23_145247/checkpoints"
train: True
test: True

extras: 
  ignore_warnings: False

hydra: 
  job_logging: 
    root:
      level: DEBUG

seed: 4

module:
  optimizer:
    _target_: torch.optim.AdamW
    lr: 5e-4
    weight_decay: 5e-4
  loss:
  #  _target_: gadme.modules.losses.asymmetric_loss.AsymmetricLossMultiLabel
    _target_: torch.nn.BCEWithLogitsLoss 
  network:
    torch_compile: False
    model: 
      checkpoint: /home/lrauch/mnt/train/runs/XCM/efficientnet/2024-02-27_175354/callback_checkpoints/efficientnet_XCM_146.ckpt



trainer: 
  max_epochs: 1
  accelerator: gpu
  devices: 1
  detect_anomaly: True
  fast_dev_run: False

datamodule:
  dataset:
    val_split: 0.1
    subset: 2000
    #n_workers: 1
    class_weights_loss: null
    class_weights_sampler: null
    classlimit: 600
    eventlimit: 3
  transforms:
    preprocessing:
      resizer:
        target_width: 1_024
  mapper:
    biggest_cluster: True
    no_call: False
  
  loaders:
    train: 
      batch_size: 3
      num_workers: 1
      shuffle: True
      pin_memory: False
    valid: 
      batch_size: 3
      num_workers: 1
      pin_memory: False
    test:
      batch_size: 3
      num_workers: 1
      pin_memory: False

tags: ["debug"]

# logger:
#   wandb:
#     tags: ${tags}
#     group: "high_sierras_aug"
#     mode: online