# @package _global_
task_name: debug

defaults:
  - override /module: multilabel.yaml
  - override /module/network: perch.yaml
  - override /datamodule: HSN.yaml
  - override /callbacks: default.yaml 
  - override /trainer: single_gpu.yaml
  - override /datamodule/transforms/waveform_augmentations: none.yaml
  - override /datamodule/transforms/spectrogram_augmentations: none.yaml

extras: 
  ignore_warnings: False

hydra: 
  job_logging: 
    root:
      level: DEBUG

seed: 2

module:
  optimizer:
    lr: 5e-4
    weight_decay: 5e-4


trainer: 
  max_epochs: 1
  accelerator: gpu
  devices: 1
  detect_anomaly: True
  fast_dev_run: False

datamodule:
  dataset:
    val_split: 0.1
    subset: 500
    n_workers: 2
    class_weights_loss: False
    class_weights_sampler: True

  loaders:
    train: 
      batch_size: 32
      num_workers: 2
      shuffle: True
      pin_memory: False
    valid: 
      batch_size: 64
      num_workers: 2
      pin_memory: False
    test:
      batch_size: 64
      num_workers: 2
      pin_memory: False

