# @package _global_
task_name: debug

defaults:
  - override /module: multilabel.yaml
  - override /module/network: eat_soundnet.yaml
  - override /datamodule: high_sierras.yaml
  - override /callbacks: default.yaml 
  - override /trainer: single_gpu.yaml
  - override /datamodule/transforms: bird_default_multilabel.yaml
  - override /datamodule/transforms/spectrogram_augmentations: none.yaml
  - override /datamodule/transforms/waveform_augmentations: none.yaml

extras: 
  ignore_warnings: False

hydra: 
  job_logging: 
    root:
      level: DEBUG

seed: 2

module:
  optimizer:
    lr: 1e-5


trainer: 
  max_epochs: 1
  accelerator: gpu
  devices: 1
  detect_anomaly: True
  fast_dev_run: False

datamodule:
  dataset:
    val_split: 0.1
    subset: 100
    n_workers: 1
    class_weights_loss: null
    class_weights_sampler: null
    classlimit: 700
    eventlimit: 5
  transforms:
    preprocessing:
      normalize_waveform: instance_normalization
    
  mapper:
    event_limit: 5
    biggest_cluster: True
    no_call: False
  

  loaders:
    train: 
      batch_size: 20
      num_workers: 1
      shuffle: True
      pin_memory: False
    valid: 
      batch_size: 20
      num_workers: 1 
      pin_memory: False
    test:
      batch_size: 20
      num_workers: 1 
      pin_memory: False

tags: ["debug"]

# logger:
#   wandb:
#     tags: ${tags}
#     group: "high_sierras_aug"
#     mode: online